---
- name: implementing tags
  hosts: all
  tasks:
      - name: install tree
        apt: 
          name: tree
          state: present
        tags: tree_installation
      - name: create user
        user:
          name: kavya
          password: divya
        tags: user_creation
      - name: copy passwd file
        copy:
          src: /etc/passwd
          dest: /tmp
...


