---
- name: implementing host scope variables
  hosts: 172.31.89.144
  tasks:
      - name: create users
        user:
           name: "{{a}}"
           password: "{{b}}"
           uid: "{{c}}"
           home: "{{d}}"
           shell: "{{e}}"
...

